### ISSUE TITLE
tensorflow 1.6 issue

### ISSUE THREAD

**Issue by vinnitu** [HasnainRaz/Skin-Segmentation-TensorFlow#2]
```
$ ./model.py
Training inititated...
Traceback (most recent call last):
  File "./model.py", line 235, in <module>
    train(image_paths, mask_paths, val_image_paths, val_mask_paths)
  File "./model.py", line 104, in train
    val_image_path, val_mask_path, augment=False, batch_size=3)
  File "/home/ai/Projects/Skin-Segmentation-TensorFlow/utility.py", line 123, in data_batch
    _parse_data, num_parallel_calls=num_threads).prefetch(30)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 792, in map
    return ParallelMapDataset(self, map_func, num_parallel_calls)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 1628, in __init__
    super(ParallelMapDataset, self).__init__(input_dataset, map_func)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 1597, in __init__
    self._map_func.add_to_graph(ops.get_default_graph())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/function.py", line 486, in add_to_graph
    self._create_definition_if_needed()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/function.py", line 321, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/function.py", line 338, in _create_definition_if_needed_impl
    outputs = self._func(*inputs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 1560, in tf_map_func
    ret = map_func(*nested_args)
  File "/home/ai/Projects/Skin-Segmentation-TensorFlow/utility.py", line 87, in _parse_data
    image_content = tf.read_file(image_paths)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 382, in read_file
    "ReadFile", filename=filename, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 533, in _apply_op_helper
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'filename' of 'ReadFile' Op has type float32 that does not match expected type of string.

```

**Comment by HasnainRaz** [comment]
What does you "train_image_paths" and "train_mask_paths" look like?

**Comment by vinnitu** [comment]
(['/home/user/Skin-Segmentation-TensorFlow/train_image/image.png'], ['/home/user/Skin-Segmentation-TensorFlow/train_mask/mask-image.png'])

**Comment by vinnitu** [comment]
seems val_image and val_mask was empty
