### ISSUE TITLE
at the end of train

### ISSUE THREAD

**Issue by vinnitu** [HasnainRaz/Skin-Segmentation-TensorFlow#3]
```
('Step:', 9998)
('Step:', 9999)
2018-03-21 22:20:25.266267: W tensorflow/core/framework/op_kernel.cc:1202] OP_REQUIRES failed at iterator_ops.cc:870 : Invalid argument: Cannot batch tensors with different shapes in component 0. First element had shape [640,427,3] and element 1 had shape [1600,1067,3].
Traceback (most recent call last):
  File "./model.py", line 235, in <module>
    train(image_paths, mask_paths, val_image_paths, val_mask_paths)
  File "./model.py", line 169, in train
    [val_image_tensor, val_mask_tensor])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1355, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot batch tensors with different shapes in component 0. First element had shape [640,427,3] and element 1 had shape [1600,1067,3].
	 [[Node: IteratorGetNext_1 = IteratorGetNext[output_shapes=[[?,480,640,3], [?,480,640,1]], output_types=[DT_FLOAT, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator_1)]]

Caused by op u'IteratorGetNext_1', defined at:
  File "./model.py", line 235, in <module>
    train(image_paths, mask_paths, val_image_paths, val_mask_paths)
  File "./model.py", line 104, in train
    val_image_path, val_mask_path, augment=False, batch_size=3)
  File "/home/ai/Projects/Skin-Segmentation-TensorFlow/utility.py", line 158, in data_batch
    next_element = iterator.get_next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 330, in get_next
    name=name)), self._output_types,
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 866, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Cannot batch tensors with different shapes in component 0. First element had shape [640,427,3] and element 1 had shape [1600,1067,3].
	 [[Node: IteratorGetNext_1 = IteratorGetNext[output_shapes=[[?,480,640,3], [?,480,640,1]], output_types=[DT_FLOAT, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator_1)]]
```

**Comment by HasnainRaz** [comment]
Utility.py updated to fix this. Should work now.
